name: Summarize Telegram Groups

on:
  schedule:
    - cron: '0 3 * * *'     # 06:00 Israel time
    - cron: '0 11 * * *'    # 14:00 Israel time
    - cron: '0 19 * * *'    # 22:00 Israel time
  workflow_dispatch:        # Allow manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run summarization script
        run: python main.py
